name: base
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.5.0=py312hfc0e8ea_100
  - annotated-types=0.6.0=py312h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - biom-format=2.1.16=py312h66e93f0_2
  - biopython=1.85=py312h66e93f0_1
  - boltons=24.1.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.1.31=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.1.1=py312h7900ff3_1
  - conda-anaconda-telemetry=0.1.2=py312h06a4308_0
  - conda-anaconda-tos=0.1.2=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=25.1.1=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py312h06a4308_0
  - conda-package-streaming=0.11.0=py312h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=43.0.3=py312h7825ff9_1
  - cuda-bindings=11.8.6=py312hd7b6ee7_0
  - cuda-profiler-api=11.8.86=0
  - cuda-python=11.8.6=pyha6e82b0_1
  - cuda-version=11.5=h6c6c5af_3
  - cudatoolkit=11.5.1=hcf5317a_9
  - cuvs=25.02.00=cuda11_py312_250213_g09c9f19_0
  - decorator=5.2.0=pyhd8ed1ab_0
  - distro=1.9.0=py312h06a4308_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - fmt=11.0.2=h434a139_0
  - frozendict=2.4.2=py312h06a4308_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.7=hfab0078_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libcuvs=25.02.00=cuda11_250213_g09c9f19_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libmamba=2.0.3=hf72d635_0
  - libmambapy=2.0.3=py312hf3f0a4e_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libraft=25.02.00=cuda11_250213_gbdcc918d_0
  - libraft-headers=25.02.00=cuda11_250213_gbdcc918d_0
  - libraft-headers-only=25.02.00=cuda11_250213_gbdcc918d_0
  - librmm=25.02.00=cuda11_250213_g39b4ccdb_0
  - libsolv=0.7.30=he621ea3_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.43.0=py312h6a678d5_1
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - mdurl=0.1.0=py312h06a4308_0
  - menuinst=2.2.0=py312h06a4308_1
  - natsort=8.4.0=pyh29332c3_1
  - nccl=2.25.1.1=h03a54cd_0
  - ncurses=6.4=h6a678d5_0
  - nlohmann_json=3.11.3=he02047a_1
  - numba=0.60.0=py312h83e6fd3_0
  - numpy=2.0.2=py312h58c1407_1
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=py312h06a4308_0
  - pandas=2.2.3=py312hf9745cd_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pip=25.0=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py312h06a4308_0
  - pydantic-core=2.27.1=py312h4aa5aa6_0
  - pygments=2.15.1=py312h06a4308_1
  - pylibraft=25.02.00=cuda11_py312_250213_gbdcc918d_0
  - pysocks=1.7.1=py312h06a4308_0
  - pytest=8.3.4=pyhd8ed1ab_1
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_1
  - rich=13.9.4=py312h06a4308_0
  - rmm=25.02.00=cuda11_py312_250213_g39b4ccdb_0
  - ruamel.yaml=0.18.6=py312h5eee18b_0
  - ruamel.yaml.clib=0.2.8=py312h5eee18b_0
  - scikit-bio=0.6.3=py312hc0a28a1_0
  - scipy=1.15.2=py312ha707e6e_0
  - setuptools=75.8.0=py312h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=pyhd8ed1ab_0
  - spdlog=1.14.1=hed91bc2_1
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.14.4=py312hc0a28a1_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.0=py312h06a4308_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py312h2c38b39_1
  - zstd=1.5.6=hc292b87_0
prefix: /home/tam/miniconda3
