name: DeepAligner
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=h93e1e8c_3
  - absl-py=2.3.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.1=py310h89163eb_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=h374c478_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-common=0.6.8=h7f98852_0
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=ha492f5f_12
  - aws-sdk-cpp=1.8.185=h721c034_1
  - biom-format=2.1.16=py310ha75aee5_2
  - biopython=1.78=py310h7f8727e_0
  - blas=1.0=mkl
  - boost-cpp=1.85.0=h44aadfe_2
  - bottleneck=1.5.0=py310hf462985_0
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.6.15=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py310h06a4308_0
  - cmake=3.31.2=h27e300b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=1.18.3=pyhd8ed1ab_0
  - debugpy=1.8.14=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py310h06a4308_0
  - flake8=7.0.0=pyhd8ed1ab_0
  - fonttools=4.58.0=py310h89163eb_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.6.0=py310h0a1d07c_0
  - fsspec=2024.6.1=pyhff2d567_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.5.0=h48cff8f_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - grpcio=1.48.2=py310he1ff14a_1
  - h5py=3.12.1=py310hc0802c4_0
  - hdf5=1.12.1=nompi_h4df4325_104
  - hnswlib=0.8.0=py310ha2bacc8_0
  - huggingface_hub=0.24.6=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=pyhd33586a_0
  - ipython=8.25.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20211102.0=cxx17_h48a1fff_3
  - libboost=1.85.0=hba137d9_2
  - libboost-devel=1.85.0=h00ab1b0_2
  - libboost-headers=1.85.0=ha770c72_2
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.4.0=hca28451_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.20=h4ab18f5_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h362ad58_1
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.8=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-base=3.9.2=py310h68603db_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.4.4=py310h89163eb_0
  - multiprocess=0.70.17=py310ha75aee5_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.10.0=py310hc51659f_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.5.0=h7b32b05_1
  - orc=1.7.4=hb3bc3d3_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.2=py310h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=9.4.0=py310h023d228_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py310h89163eb_0
  - protobuf=3.20.3=py310heca2aa9_1
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=11.0.0=py310h468efa6_1
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=py310h06a4308_0
  - pytest=7.4.4=pyhd8ed1ab_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-levenshtein=0.12.2=py310h5764c6d_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py310ha75aee5_2
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - pyzmq=26.4.0=py310h71f11fc_0
  - qhull=2020.2=h4bd325d_2
  - rapidfuzz=3.5.2=py310hc6cd4ac_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h8228510_1
  - regex=2024.7.24=py310ha75aee5_1
  - requests=2.32.3=py310h06a4308_1
  - rhash=1.4.3=hdbd6064_0
  - safetensors=0.4.4=py310h505e2c1_1
  - scikit-bio=0.6.3=py310hf462985_0
  - scikit-learn=1.5.1=py310h27f47ee_1
  - scipy=1.13.1=py310h5f9d8c6_1
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.2=py310h261611a_0
  - sympy=1.13.2=pyh04b8f61_3
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.17.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h6c63255_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.19.1=py310h320607d_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchtriton=3.1.0=py310
  - tornado=6.5.1=py310ha75aee5_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.44.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.0=py310h89163eb_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.22.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - boto3==1.26.99
      - botocore==1.29.99
      - defusedxml==0.7.1
      - faiss-gpu==1.7.2
      - jmespath==1.0.1
      - jsonlines==4.0.0
      - networkx==3.1
      - neuspell==1.0.0
      - numpy==1.25.2
      - onnx==1.15.0
      - openvino==2024.3.0
      - openvino-dev==2024.3.0
      - openvino-telemetry==2025.1.0
      - pytorch-pretrained-bert==0.6.2
      - s3transfer==0.6.2
      - scann==1.4.0
      - sentencepiece==0.1.97
      - triton==3.0.0
      - urllib3==1.26.20
prefix: /home/tam/miniconda3/envs/DeepAligner
