name: DeepReadMapper
channels:
  - conda-forge
  - defaults
dependencies:
  # Build tools
  - cmake
  - make
  - cxx-compiler  # Provides g++/gcc

  # Core dependencies
  - openvino
  - faiss-cpu
  - zlib
  - llvm-openmp
  - cereal
